export const queryKeys = {
  login: 'login',
  userMe: 'user-me',
  todos: 'todos',
  todoRandom: 'todo-random',
  todoAdd: 'todoAdd',
  todoSingle: 'todoSingle',
  todoDelete: 'todoDelete',
  userSingle: (userId: number) => `${userId} user`,
  userIdCarts: (userId: number) => `carts by ${userId} user`,
  userIdPosts: (userId: number) => `posts by ${userId} user`,
  userIdTodos: (userId: number) => `todos by ${userId} user`,
  allPosts: 'all-posts',
  postSingle: (postId: string) => `${postId} post`,
  postSearch: 'post-search',
  postAdd: 'post add',
  postDelete: 'post-delete',
  postUpdate: 'post update',
  postComment: (postId: string) => `${postId} post comment`,
}
