#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint
npm run types
npm run format
npm run check:packages

if git diff --staged --quiet; then
  echo "No changes to commit after formatting."
  exit 1
fi

exit 0